### ISSUE TITLE
The addon-enable checkbox can't be checked

### ISSUE THREAD

**Issue by coolq1000** [agoose77/bge_network_addon#10]
Hi,
I am a programmer myself, I use Blender 'BGE'. Although I have only started about six months ago, I can't seem to find why I can't use this?
okay, here's more detail:
I followed your tut as closely as possible, I don't know what I did wrong, so what I have done is I made a new folder, called 'Multiplayer' then I extracted all the stuff from the 'PyAuthServer' into it. I opened a new Command Prompt and ran the command (I set all the PATH stuff up ages ago.) you said. It worked, soon it said it had finished, so I then opened up Blender and selected the add-on I downloaded before. When I try to enable it, it says:

Traceback (Most recent call last)
... (Lots of stuff)
No module found called 'game_system'
the reason I didn't write the middle is because I did it by hand.
Thanks in advance.
-Coolq

P.S: Here's a picture.
![untitled](https://cloud.githubusercontent.com/assets/5827201/8427539/7f7368b6-1f5b-11e5-9791-6d1054568c9b.png)

**Comment by agoose77** [comment]
Did you install it into Python, or blender site packages?
If Python, check your site packages are in your PythonPath.

Also, which version of the PyAuthServer did you download?

**Comment by coolq1000** [comment]
I really don't know what you mean about Python path and Blender site packages.
I have Downloaded V1.1.1 of your PyAuthServer.

**Comment by coolq1000** [comment]
ooooh, yeah I installed it with, Python if that's what you mean?

-Coolq

**Comment by coolq1000** [comment]
YAY!
I got it working! I used the Blender site packages instead!

Thank you so much for making this add-on!
-Coolq

**Comment by agoose77** [comment]
That's great. I've recorded a video, and I'll update the docs to make this even more clear.
Thanks for your help :+1:

**Comment by coolq1000** [comment]
Also, do you mind showing me some links to Tutorials on YouTube? Because I don't know how to use it :\
I found in the Logic Editor the panel, it was disabled so I went to scenes and enabled it. It works now but I can't seem to get it working...

Anyway thanks for the help too :+1:

**Comment by agoose77** [comment]
There are video tutorials here
https://www.youtube.com/playlist?list=PLNBw_-aJfrjcx75d-SltdO-b08v_HhJ4o
Some of them might not directly correlate with the latest version, but I'll usually mention that in a later video.

**Comment by adriansnetlis** [comment]
Well, I have basicly the same problem, but using python setup.py install failed(first line of setup.py couldn't have completed), but using site-packages shows the same error(https://github.com/agoose77/bge_network_addon/issues/13) :(
