### ISSUE TITLE
Network must be enabled for the scene, but how shall I do that?

### ISSUE THREAD

**Issue by jnsiemer** [agoose77/bge_network_addon#11]
Under the Properties is standing Network, but under Network is not the normal thing, like the options, there is just written: Networking must be enabled for this scene. How can I stop that?

**Comment by agoose77** [comment]
That means you need to "enable networking for this _scene_" ;)

Go to Scene Properties -> Network -> Enable for this scene.

For more questions, view the tutorials
https://www.youtube.com/playlist?list=PLNBw_-aJfrjcx75d-SltdO-b08v_HhJ4o
