### ISSUE TITLE
Paid game?

### ISSUE THREAD

**Issue by coolq1000** [agoose77/bge_network_addon#12]
Hey,
Thanks for showing me those links, they are really helpful!

My goal is to make a game with multiplayer, your add-on seems to work, so would you allow it if I made a paid game with your add-on? also could I get your Skype details?
My Skype address is: coolq.b (May be incorrect, But i'm pretty sure it's not)

P.S: I don't mind if you add me or I add you.

Thanks
-Coolq

**Comment by coolq1000** [comment]
Hello?

**Comment by agoose77** [comment]
You certainly can :+1:
