### ISSUE TITLE
Getting error when trying to enable add-on

### ISSUE THREAD

**Issue by adriansnetlis** [agoose77/bge_network_addon#13]
Traceback (most recent call last):
  File "/opt/Blender/2.75/scripts/modules/addon_utils.py", line 324, in enable
    mod = **import**(module_name)
  File "/home/user/.config/blender/2.75/scripts/addons/bge_network_addon/**init**.py", line 44, in <module>
    from game_system.configobj import ConfigObj
ImportError: No module named 'game_system.configobj'

This is the error I get when pressing on checkbox!

**Comment by agoose77** [comment]
Have you downloaded and correctly placed the modules from PyAuthServer into site-packages / used the installer?

**Comment by adriansnetlis** [comment]
Yes... I placed the 3 folders you hsow in tutorial in /opt/Blender/2.75/python/lib/python3.4/site-packages/

**Comment by agoose77** [comment]
Is there a site-packages folder in 2.75/python/lib
That should be the install path.

Running setup.py won't work if you don't have setuptools installed.

**Comment by agoose77** [comment]
Closing until further information is available
