### ISSUE TITLE
Blender doesn't close correctly if "game_system" file in Blender side-packages

### ISSUE THREAD

**Issue by Maujoe** [agoose77/bge_network_addon#15]
It's seems like there is something wrong with the game_system module because when it's in the blender side-packeges folder blender doesn't close correctly. If I close blender the window close but in the task manager the blender.exe and blenderapp.exe process are still aktive. 

The blender version is 2.75 (I also test it with 2.75a).

**Comment by agoose77** [comment]
I have since fixed this - a Python thread wasn't being closed.
Thank you for reporting this.
