### ISSUE TITLE
cant change between Client / Server

### ISSUE THREAD

**Issue by Bratwurst54** [agoose77/bge_network_addon#18]
after i installed the addon successfuly and turned "Networking" in the Scene Settings to True, i cant change between the Client or Server mode in the world settings, because it isnt displayed. whats the problem with that ?!

**Comment by agoose77** [comment]
This setting no longer exists. It is configured from logic bricks using a set_netmode message (see wiki)

**Comment by Bratwurst54** [comment]
oh ok thanks for the fast reply :D
