### ISSUE TITLE
Crash at connecting to server: module missing and attribute error.

### ISSUE THREAD

**Issue by Cryofear** [agoose77/bge_network_addon#19]
When starting up the template.blend (example blend) and trying to connect to the server, the following error appears. Tested on blender versions 2.74(64-bit) and 2.76(32-bit) and on a separate file with no ties to the template blend.

![image](https://cloud.githubusercontent.com/assets/17141743/12916323/ba79d32e-cf31-11e5-9743-0945f4244ea4.png)

**Comment by agoose77** [comment]
This happens because no game rules are assigned to the game. If this was a bug, it's probably been fixed. Some of the templates were corrupted in a recent version, but in the latest I have one or two working versions that you may try.
