### ISSUE TITLE
The addon can't be enabled

### ISSUE THREAD

**Issue by svenar-nl** [agoose77/bge_network_addon#20]
Hi,
I am trying to install your addon, the PyAuthServer is successfully installed but the addon itself can't be enabled.

![errorbgenetworkaddon](https://cloud.githubusercontent.com/assets/11473832/13640242/23ef3d50-e614-11e5-8ead-f742d8898cfa.png)

It is on Ubuntu 15.10
And I installed pyAuthServer 1.1.1 and the addon 1.0.5 (also tried 1.0.6)

**Comment by agoose77** [comment]
I believe I have fixed this in the newest version. Please manually remove the addon and the network code (both MUST be removed) and then try installing it again!
