### ISSUE TITLE
Falied to install

### ISSUE THREAD

**Issue by VScalia** [agoose77/bge_network_addon#7]
tried to install from file, but blender said it couldn't find the "network", "game_system" or "bge_game_system". I know this is a bug because I tried it again three more times and it worked on the third. I tried to install the same file all four times.

**Comment by agoose77** [comment]
Did you read the install instructions, and download the dependency? (PyAuthServer)

https://github.com/agoose77/bge_network_addon/wiki/Installation-Guide

Thanks for the report.

**Comment by VScalia** [comment]
Read and followed the installation instructions. New-ish to blender: do you have a link to the dependency?

**Comment by agoose77** [comment]
The error indicates you didn't download py-auth-server, which is the first part of the tutorial. Where did you put the modules from it (network, bge_game_system, game_system)

**Comment by VScalia** [comment]
for some reason I couldn't copy them direct to [computer>OS>Program files>Blender Foundation>Blender>2.74>python>lib>site-packages] so I copied a folder called "temporary transfers for blender" and then to the above location. I did download py-auth-server.

Just noticed that the files (network, ect…) are folders, were there certain modules I needed to copy?

**Comment by agoose77** [comment]
To clarify, you copied "network/", "game_system/", "bge_game_system/" to "Blender Foundation/Blender/2.74/python/lib/site-packages/" ?

**Comment by VScalia** [comment]
yessir. It would also seem that the time that it actually worked, I installed the "network render". So I guess the real problem is that it doesn't show up on the addon list after installing from file. sorry about that.

**Comment by agoose77** [comment]
Please double-check that you're using the same blender version (2.74) as you're copying these files to. 
Then, if that is not the issue, please run the following individual commands in the built-in Python interpreter in Blender, one after the other, and upload any errors (screenshot) if you fail.
1. import network
2. import game_system
