### ISSUE TITLE
Networking not enabled for scene

### ISSUE THREAD

**Issue by nickhaidos** [agoose77/bge_network_addon#9]
After following all the steps(and checking the box to enable the add on), it kept saying that this addon is not enabled for this scene.

**Comment by nickhaidos** [comment]
And now Blender freezes and I can't close it.

**Comment by nickhaidos** [comment]
By the way, I use Ubunntu 14.04 LTS.

**Comment by agoose77** [comment]
You need to enable the networking for the scene (Scene properties -> Use Network)
